### ISSUE TITLE
Document the exposed player instance

### ISSUE THREAD

**Issue by suterma** [vue-youtube/docs#3]
Hi, this is a great library, and I like it very much, including the concise documentation. 

I want to further control the youtube instance, with seek operations and getting the current position, thus I was looking on how to extend this library.

However, after a moment at looking into the code I found that you already expose the player instacance, via the `instance` shallow ref. This makes it very easy for me. Thanks for that, but I ask you also to please document this, as I am sure, other will benefit from it too.

**Comment by Techassi** [comment]
Sure, I can document the usage of `instance` more prominently. This will be online as soon as I implement your requested feature https://github.com/vue-youtube/vue-youtube/issues/8 as it also needs documentation adjustments.

**Comment by Techassi** [comment]
This is now documented here: https://vue-youtube.github.io/docs/usage/composable#player-instance

Let me know if you want to improve the documentation even further.

**Comment by suterma** [comment]
Thanks, this will benefit this great component!
