### ISSUE TITLE
Dynamic loading of vue-youtube

### ISSUE THREAD

**Issue by nathanchase** [vue-youtube/docs#4]
I'd like to do a dynamic load of vue-youtube, rather than a plugin that adds to my Nuxt 3 entry bundle.

Something like this:
```
// components/YourComponent.vue
<template>
  <div v-if="youtubeReady">
    <!-- Your component's template -->
    <YoutubeIframe video-id="your-video-id" />
  </div>
</template>

<script>
import { ref, onMounted } from 'vue';

const nuxtApp = useNuxtApp(); // access the Nuxt app context

let youtubeManager; // Define a variable to hold the YouTube manager

const loadYoutube = async () => {
  const { createManager } = await import('@vue-youtube/core');
  const { YoutubeIframe } = await import('@vue-youtube/component');

  youtubeManager = createManager(); // Initialize the YouTube manager
  nuxtApp.vueApp.use(manager); // <- this is where I think the issue lies
};

export default {
  setup() {
    const youtubeReady = ref(false);

    onMounted(() => {
      // Load the YouTube package when the component is mounted
      loadYoutube().then(() => {
        youtubeReady.value = true;
      });
    });

    return {
      youtubeReady,
    };
  },
};
</script>
```
The problem is, by doing it this way, Vue complains with an error of `App already provides property with key "vue-youtube". It will be overwritten with the new value. `

Is there some way to dynamically use vue-youtube rather than having to provide it to vueApp?

**Comment by suterma** [comment]
You have two options:
- Do it in your "player" component, like I do currently: https://github.com/suterma/replayer-pwa/blob/3289aadc02a00861c13ff0c26fb97199f4a7d817/src/components/track/TrackYouTubeElement.vue#L147C1-L160C2
- Do it the official way with `deferLoading`: https://vue-youtube.github.io/docs/usage/manager#deferloading

**Comment by Techassi** [comment]
Regarding Nuxt support: This is indeed very tricky. There seems to be an issue with the provide/inject API. To dynamically load the required scripts, it is indeed recommended to use `deferLoading` as @suterma mentioned. Let me know if you need any further support!

**Comment by nathanchase** [comment]
Perfect. Thank you @suterma @Techassi.
